version: '3.8'

services:
  backend:
    image: job-application-tracker
    build: ./backend
    ports:
      - "8080:8080"
      - "443:443"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/job_app_tracker
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      APP_URL: ${APP_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      KEY_STORE_ALIAS: ${KEY_STORE_ALIAS}
      KEY_STORE_PASS: ${KEY_STORE_PASS}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      PORT: ${PORT}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}

    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: job_app_tracker
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
