version: '3'
services:
  app:
    image: job-application-tracker
    build: .
    ports:
      - "8080:8080"
      - "443:443"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/job_app_tracker
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      KEY_STORE_ALIAS: ${KEY_STORE_ALIAS}
      KEY_STORE_PASS: ${KEY_STORE_PASS}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      PORT: ${PORT}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}

    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: job_app_tracker
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
